### PR TITLE
Upgrade rocksdb to latest tag v6.19.3

### LINKED ISSUE #225: [BUG] Unable to build.
Attempting to compile as per instructions on Readme. Unable to build.

image

`./db/version_edit.h:86:8: error: implicitly-declared ‘constexpr rocksdb::FileDescriptor::FileDescriptor(const rocksdb::FileDescriptor&)’ is deprecated [-Werror=deprecated-copy]`

 - OS: Ubuntu 20.04
 - GCC/G++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
 - GNU Make 4.2.1

**To Reproduce**
1. Build as per instructions on README

### PR DESCRIPTION
**Pull request by karelrooted**
Fix can't compile on GCC(>=9) (resolves #225  rocksdb fix this at PR https://github.com/facebook/rocksdb/pull/5553)
Fix can't auto resume after no space error (rocksdb  add the auto resume feature at PR https://github.com/facebook/rocksdb/pull/6765)

### CODE REVIEW

**Comment by karelrooted** [comment]
Successly compile on Docker centos 8.2 ( gcc 8.3.1), Docker ubuntu 20.04 (gcc  9.3.0), Mac OS 10.15.7 (cmake)

**Review by git-hulk — APPROVED** [review]
LGTM

**Comment by ShooterIT** [comment]
cool, so now rocksdb is latest release

**Review by ShooterIT — APPROVED** [review]
